# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/jekynewage.github.io" # the subpath of your site, e.g. /blog/
url: "https://jekynewage.github.io" # the base hostname & protocol for your site

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/lantoniotrento
  - title: facebook
    url: https://facebook.com/lantoniotrento
  - title: google-plus
    url: https://plus.google.com/+AntoniotrentoIt
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
